### ISSUE TITLE
Move this module to the terminal-app repo

### ISSUE THREAD

**Issue by ricardomv** [papyros/qmltermwidget#1]
It would make more sense to have this repo in the terminal app repository under `src/plugins` like we do in the files-app.

**Comment by ricardomv** [comment]
Since this uses qmake as the build system i see it would be pain to support. Maybe leaving things as they are isn't as bad as i thought.

**Comment by iBelieve** [comment]
Well, the idea is that we send all changes upstream via pull requests (as I did with Swordfish90/qmltermwidget#12), so it needs to be a separate repo.

**Comment by ricardomv** [comment]
Yes i saw that,
